export const GET_MENU = 'GET_MENU'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAIL = 'GET_MENU_FAIL';

export const GET_MY_COMPANIES = 'GET_MY_COMPANIES';
export const GET_MY_COMPANIES_SUCCESS = 'GET_MY_COMPANIES_SUCCESS';
export const GET_STARRED_COMPANIES_SUCCESS = 'GET_STARRED_COMPANIES_SUCCESS';
export const GET_MY_COMPANIES_FAIL = 'GET_MY_COMPANIES_FAIL';

export const GET_COUNTRY_CODE = 'GET_COUNTRY_CODE';
export const GET_COUNTRY_CODE_SUCCESS = 'GET_COUNTRY_CODE_SUCCESS';

export const GET_CLIENT_TYPE = 'GET_CLIENT_TYPE';
export const GET_CLIENT_TYPE_SUCCESS = 'GET_CLIENT_TYPE_SUCCESS';
export const GET_CONTACT_TYPE_SUCCESS = 'GET_CONTACT_TYPE_SUCCESS';

export const GET_ACCOUNT_CODE = 'GET_ACCOUNT_CODE';
export const GET_ACCOUNT_CODE_SUCCESS = 'GET_ACCOUNT_CODE_SUCCESS';

export const STARRED_COMPANY = 'STARRED_COMPANY';
export const STARRED_ADD = 'STARRED_ADD';
export const STARRED_DELETE = 'STARRED_DELETE';

export const GET_BANK_LIST = 'GET_BANK_LIST'
export const GET_BANK_LIST_SUCCESS = 'GET_BANK_LIST_SUCCESS'

export const RESET_PROPERTIES = 'RESET_PROPERTIES'